//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetProviderToporova
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderService
    {
        public int Id { get; set; }
        public int Serviceid { get; set; }
        public int OrderId { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public string Active { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Service Service { get; set; }
    }
}
